name: test-actions
description: Test custom GitHub Action
author: pgleska

# Define your inputs here.
inputs:
  host:
    description: RDepot host
    required: true
  token:
    description: RDepot access token
    required: true

runs:
  using: docker
  image: docker://registry.openanalytics.eu/openanalytics/rdepot-cli:2.1.1
  entrypoint: /bin/sh -c echo "Hello from test world, $RDEPOT_HOST"
  env:
    RDEPOT_HOST: ${{ inputs.host }}
    RDEPOT_TOKEN: ${{ inputs.token }}
