name: test-actions
description: Test custom GitHub Action
author: pgleska

# Define your inputs here.
inputs:
  host:
    description: RDepot host
    required: true
  token:
    description: RDepot access token
    required: true

runs:
  using: docker
  image: docker://registry.openanalytics.eu/openanalytics/rdepot-cli:latest
  # entrypoint: "/github/workspace/entrypoint.sh"
  args:
    - submit
  env:
    RDEPOT_HOST: ${{ inputs.host }}
    RDEPOT_TOKEN: ${{ inputs.token }}
