name: test-actions
description: Test custom GitHub Action
author: pgleska

# Define your inputs here.
inputs:
  host:
    description: RDepot host
    required: true
  username:
    description: RDepot username
    required: true
  token:
    description: RDepot access token
    required: true
  file:
    description: File to be uploaded
    required: true
  repository-name:
    description: Repository name
    required: true
  replace-flag:
    description: Value of replace flag
    required: false
    default: "false"

runs:
  using: docker
  image: docker://registry.openanalytics.eu/openanalytics/rdepot-cli:latest
  args:
    - packages
    - submit
    - -f
    - ${{ inputs.file }}
    - --repo
    - ${{ inputs.repository-name }}
    - --replace=${{ inputs.replace-flag }}
  env:
    RDEPOT_HOST: ${{ inputs.host }}
    RDEPOT_TOKEN: ${{ inputs.token }}
