name: test action

on: push

jobs:
  test-action:
    name: test action 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Test Action
        id: test-action
        uses: pgleska/test-actions@main
        with:
          host: test-xyz
          token: 123abcd
